#!/usr/bin/env python3
"""
Vendor the UI webfonts into frontend/fonts/ (DEPLOYMENT_REVIEW.md 3.6).

A security-product demo that phones out to fonts.gstatic.com on every page load
is a bad look, and the CDN breaks air-gapped/enterprise deployments outright.
Self-hosting also lets the CSP drop every remote origin.

Run this only when a family or weight changes:

    python tools/fetch_fonts.py

Then commit frontend/fonts/ and the regenerated frontend/fonts.css.
"""
import hashlib
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "frontend" / "fonts"

CSS_URL = ("https://fonts.googleapis.com/css2"
           "?family=Lexend:wght@300;400;500;600;700"
           "&family=Source+Sans+3:wght@400;500;600;700"
           "&family=JetBrains+Mono:wght@400;500;600&display=swap")

# Google only serves woff2 to modern UA strings; with the default urllib UA it
# returns the ancient truetype stylesheet instead.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

# The app's five UI languages are en/ko/zh-TW/zh-CN/ja. None of these families
# ship CJK glyphs, so CJK text falls back to system fonts either way — shipping
# cyrillic/greek/vietnamese subsets would be dead weight.
KEEP_SUBSETS = {"latin", "latin-ext"}

# Weight range to declare per family. These are variable fonts: Google returns
# the SAME file for every weight in the range, so one @font-face with a range
# replaces N identical downloads.
RANGES = {"Lexend": "300 700", "Source Sans 3": "400 700", "JetBrains Mono": "400 600"}

LICENSE_URL = "https://raw.githubusercontent.com/google/fonts/main/ofl/lexend/OFL.txt"

HEADER = """/*
 * Self-hosted webfonts — no third-party request on load.
 *
 * GENERATED by tools/fetch_fonts.py. Do not edit by hand.
 *
 * latin + latin-ext only: these families ship no CJK glyphs, so the ja/ko/zh
 * UI languages already fall back to system fonts either way.
 *
 * One @font-face per family+subset with a WEIGHT RANGE, not one per weight:
 * these are variable fonts and Google serves a byte-identical file for every
 * weight, so per-weight faces would ship the same bytes 5 times over.
 *
 * Lexend, Source Sans 3 and JetBrains Mono are SIL OFL 1.1 — see
 * fonts/OFL.txt and fonts/README.txt for the required notices.
 */
"""


def _get(url: str, binary: bool = False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    data = urllib.request.urlopen(req, timeout=30).read()
    return data if binary else data.decode("utf-8")


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    css = _get(CSS_URL)
    blocks = re.findall(r"/\* ([a-z-]+) \*/\s*(@font-face \{.*?\})", css, re.S)
    if not blocks:
        print("no @font-face blocks parsed — did the css2 response format change?",
              file=sys.stderr)
        return 1

    seen: dict[str, str] = {}          # content hash -> filename, for dedupe
    faces: dict[tuple[str, str], str] = {}
    total = 0

    for subset, blk in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        fam = re.search(r"font-family: '([^']+)'", blk).group(1)
        if (fam, subset) in faces:
            continue                   # already have this family+subset
        url = re.search(r"url\((https://[^)]+\.woff2)\)", blk).group(1)
        data = _get(url, binary=True)
        if data[:4] != b"wOF2":        # fail closed rather than commit garbage
            print(f"{fam}/{subset}: not a woff2 payload", file=sys.stderr)
            return 1
        digest = hashlib.sha256(data).hexdigest()
        if digest in seen:
            name = seen[digest]
        else:
            name = f"{fam.lower().replace(' ', '-')}-{subset}.woff2"
            (OUT / name).write_bytes(data)
            seen[digest] = name
            total += len(data)
            print(f"  {name:34s} {len(data):>7,d} B")
        faces[(fam, subset)] = (name, re.search(r"unicode-range: ([^;]+);", blk).group(1))

    out = [HEADER]
    for (fam, subset), (name, urange) in faces.items():
        out.append(f"""/* {fam} · {subset} */
@font-face {{
  font-family: '{fam}';
  font-style: normal;
  font-weight: {RANGES[fam]};
  font-display: swap;
  src: url('fonts/{name}') format('woff2');
  unicode-range: {urange};
}}""")

    (OUT.parent / "fonts.css").write_text("\n".join(out) + "\n", encoding="utf-8")

    try:
        (OUT / "OFL.txt").write_text(_get(LICENSE_URL), encoding="utf-8")
    except Exception as exc:            # noqa: BLE001 — advisory, not fatal
        print(f"warning: could not fetch OFL.txt ({exc}); add it manually", file=sys.stderr)

    print(f"\n{len(seen)} files, {total:,} bytes, {len(faces)} @font-face rules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
